# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Meninki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Meninki
  pod 'GoogleSignIn'
  
  pod 'Alamofire', '~> 5.6.4'
  pod 'Kingfisher', '~> 7.0'

  pod 'EasyPeasy', '~> 1.9.0'
  pod 'Parchment', '~> 3.2'
  pod 'FloatingPanel'
  pod 'TLPhotoPicker', '~> 2.1.0'
  pod 'SkeletonView'
  pod 'Localize-Swift', '~> 3.2'

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
